CREATE TABLE users (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  email VARCHAR(255) UNIQUE
);

CREATE TABLE loans (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  total DOUBLE PRECISION,
  user_id BIGINT NOT NULL,
CONSTRAINT FK_USER_LOAN FOREIGN KEY (user_id) REFERENCES users(id)
);